import 'dart:convert';
import 'dart:math' as math;
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart' show StringCharacters;

/// One character as the school's handwriting sheet draws it: its dots, in
/// units of its script's letter height, measured from its left edge (x) and
/// from the line it sits on (y, negative above it).
class Letterform {
  Letterform._(this.script, this.width, this.dots, this.links);

  factory Letterform._fromJson(Map<String, dynamic> json) {
    final flat = (json['d'] as List<dynamic>).cast<num>();
    final dots = [
      for (var i = 0; i + 1 < flat.length; i += 2)
        Offset(flat[i].toDouble(), flat[i + 1].toDouble()),
    ];
    return Letterform._(
      json['s'] as String? ?? '',
      (json['w'] as num?)?.toDouble() ?? 0,
      dots,
      _linksBetween(dots),
    );
  }

  final String script;
  final double width;
  final List<Offset> dots;

  /// Pairs of neighbouring dots, joined to draw the letter as a solid line.
  final List<(int, int)> links;

  /// Neighbours are about one dot-gap apart; anything further is across a
  /// gap in the letter (the dot of an i) and stays unjoined.
  static List<(int, int)> _linksBetween(List<Offset> dots) {
    if (dots.length < 2) return const [];
    final gaps = <double>[];
    for (var i = 0; i < dots.length; i++) {
      var best = double.infinity;
      for (var j = 0; j < dots.length; j++) {
        if (i == j) continue;
        final d = (dots[i] - dots[j]).distance;
        if (d > 0 && d < best) best = d;
      }
      if (best.isFinite) gaps.add(best);
    }
    gaps.sort();
    final reach = gaps[gaps.length ~/ 2] * 1.55;
    return [
      for (var i = 0; i < dots.length; i++)
        for (var j = i + 1; j < dots.length; j++)
          if ((dots[i] - dots[j]).distance <= reach) (i, j),
    ];
  }
}

/// The school's letterforms, loaded once from the app's own assets.
///
/// English, Hindi and Gujarati letters, their numbers, and the pre-writing
/// patterns — every character a child meets in tracing, questions and games,
/// drawn the way the school writes it rather than in the app's typeface.
/// Generated by scripts/content/letterforms/build.py from the school's sheet.
class Letterforms {
  Letterforms._(this._glyphs, this.patternNames);

  final Map<String, Letterform> _glyphs;

  /// Pattern keys ("pattern-zigzag") to what a person calls them.
  final Map<String, String> patternNames;

  static const _file = 'assets/letterforms/letterforms.json';

  static Letterforms? _current;
  static Future<Letterforms>? _loading;

  /// The loaded set, or null before [load] has finished.
  static Letterforms? get current => _current;

  /// Loads the set. Never throws: without it every character is simply drawn
  /// in the app's typeface, as before.
  static Future<Letterforms> load([AssetBundle? bundle]) {
    return _loading ??= () async {
      try {
        final raw = await (bundle ?? rootBundle).loadString(_file);
        final json = jsonDecode(raw) as Map<String, dynamic>;
        final glyphs = (json['glyphs'] as Map<String, dynamic>).map(
          (key, value) => MapEntry(
            key,
            Letterform._fromJson(value as Map<String, dynamic>),
          ),
        );
        final patterns = (json['patterns'] as Map<String, dynamic>? ?? const {})
            .map((key, value) => MapEntry(key, value as String));
        return _current = Letterforms._(glyphs, patterns);
      } on Object {
        _loading = null;
        return Letterforms._(const {}, const {});
      }
    }();
  }

  /// Built from data already in hand — for tests.
  factory Letterforms.from(Map<String, dynamic> json) => Letterforms._(
    (json['glyphs'] as Map<String, dynamic>).map(
      (key, value) =>
          MapEntry(key, Letterform._fromJson(value as Map<String, dynamic>)),
    ),
    (json['patterns'] as Map<String, dynamic>? ?? const {}).map(
      (key, value) => MapEntry(key, value as String),
    ),
  );

  Letterform? operator [](String glyph) => _glyphs[glyph];

  /// The characters of [text] in the school's hand, or null when any of them
  /// is not on the sheet (an emoji, a word in another script) — the caller
  /// draws those in the typeface instead.
  ///
  /// A key on the sheet is taken whole first, so "क्ष", "१०" and
  /// "pattern-zigzag" are one shape; anything else goes a character at a time
  /// ("10" is a one and a nought).
  List<Letterform>? shapesFor(String text) {
    final key = text.trim();
    if (key.isEmpty) return null;
    final whole = _glyphs[key];
    if (whole != null) return [whole];

    final out = <Letterform>[];
    for (final char in key.characters) {
      if (char.trim().isEmpty) continue;
      final shape = _glyphs[char];
      if (shape == null) return null;
      out.add(shape);
    }
    return out.isEmpty ? null : out;
  }
}

/// Characters laid out side by side on one line, ready to paint.
class LetterformRun {
  LetterformRun(List<Letterform> shapes) {
    const gap = 0.14;
    var x = 0.0;
    for (final shape in shapes) {
      final base = dots.length;
      for (final dot in shape.dots) {
        dots.add(Offset(dot.dx + x, dot.dy));
      }
      for (final (a, b) in shape.links) {
        links.add((a + base, b + base));
      }
      x += shape.width + gap;
    }
    if (dots.isEmpty) {
      bounds = Rect.zero;
      return;
    }
    var left = double.infinity, top = double.infinity;
    var right = -double.infinity, bottom = -double.infinity;
    for (final dot in dots) {
      left = math.min(left, dot.dx);
      top = math.min(top, dot.dy);
      right = math.max(right, dot.dx);
      bottom = math.max(bottom, dot.dy);
    }
    bounds = Rect.fromLTRB(left, top, right, bottom);
  }

  final dots = <Offset>[];
  final links = <(int, int)>[];
  late final Rect bounds;
}
